server:
  port: 8080

jwt_secret: changeme-secret
platform_jwt_secret: changeme-platform-secret
app_pool_size: 5

database:
  host: localhost
  port: 5433
  user: rocket
  password: rocket
  name: rocket
  pool_size: 10
