server:
  port: 8080

jwt_secret: changeme-secret
platform_jwt_secret: changeme-platform-secret
app_pool_size: 5

storage:
  driver: local
  local_path: ./uploads
  max_file_size: 10485760

database:
  driver: postgres
  # driver: sqlite
  # data_dir: ./data
  host: localhost
  port: 5433
  user: rocket
  password: rocket
  name: rocket
  pool_size: 50
