server:
  port: 8080

jwt_secret: changeme-secret
platform_jwt_secret: changeme-platform-secret
app_pool_size: 5

storage:
  driver: local
  local_path: ./uploads
  max_file_size: 10485760

# AI Schema Generator (or use env vars: ROCKET_AI_BASE_URL, ROCKET_AI_API_KEY, ROCKET_AI_MODEL)
# ai:
#   base_url: https://api.openai.com/v1
#   api_key: sk-your-key-here
#   model: gpt-4o

database:
  driver: postgres       # "postgres" or "sqlite"
  host: localhost
  port: 5433
  user: rocket
  password: rocket
  name: rocket
  pool_size: 50
  # path: ./data         # SQLite: directory for database files
